services:
  - type: web
    name: mood-based-music-recommendation-system
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "streamlit run app.py --server.port $PORT --server.address=0.0.0.0"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"