services:
  - type: web
    name: mood-based-music-recommendation-system
    runtime: python
    pythonVersion: "3.11"
    buildCommand: "./build.sh"
    startCommand: "streamlit run app.py --server.port $PORT --server.address=0.0.0.0"